# Generated by Django 5.1.15 on 2026-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasualDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('number_of_guest', models.IntegerField(default=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('we_are_allowed_to_take_pictures_of_you_and_your_guest', models.BooleanField(db_column='picture_consent', default=True)),
                ('we_are_allowed_to_take_pictures_of_your_apartment', models.BooleanField(db_column='apartment_consent', default=True)),
                ('we_are_allowed_to_use_your_event_content_for_our_business_promotions', models.BooleanField(db_column='content_consent', default=True)),
                ('menu_type', models.CharField(choices=[('M1', 'Menu 1'), ('M2', 'Menu 2')], default='M1', max_length=2)),
                ('bread', models.CharField(choices=[('F', 'Focaccia'), ('C', 'Ciabatta'), ('S', 'Sourdough'), ('H', 'Herbal bun'), ('G', 'Garlic bread'), ('CH', 'Challah')], default='F', max_length=2)),
                ('side_one', models.CharField(choices=[('BMP', 'Buttering mashed potatoes'), ('CGP', 'Cheesy garlic roasted butter potatoes'), ('PF', 'Potatoes fondant'), ('CBP', 'Creamy baby potatoes'), ('SPR', 'OSE special fried rice'), ('SSF', 'Spaghetti stir fry'), ('CJ', 'Coriander jasmine'), ('SAJ', 'Smoked asun jollof ')], default='BMP', max_length=3)),
                ('side_two', models.CharField(choices=[('BMP', 'Buttering mashed potatoes'), ('CGP', 'Cheesy garlic roasted butter potatoes'), ('PF', 'Potatoes fondant'), ('CBP', 'Creamy baby potatoes'), ('SPR', 'OSE special fried rice'), ('SSF', 'Spaghetti stir fry'), ('CJ', 'Coriander jasmine'), ('SAJ', 'Smoked asun jollof ')], default='CGP', max_length=3)),
                ('vegetable_one', models.CharField(choices=[('RC', 'Roasted carrot'), ('BT', 'Broccoli tempura'), ('SM', 'Sautéed mushroom'), ('PO', 'Pickled onion'), ('MP', 'Mixed bell pepper'), ('SS', 'Sautéed spinach'), ('AB', 'Assorted bread')], default='RC', max_length=2)),
                ('vegetable_two', models.CharField(choices=[('RC', 'Roasted carrot'), ('BT', 'Broccoli tempura'), ('SM', 'Sautéed mushroom'), ('PO', 'Pickled onion'), ('MP', 'Mixed bell pepper'), ('SS', 'Sautéed spinach'), ('AB', 'Assorted bread')], default='BT', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomisedDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('service_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmberDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('number_of_guest', models.IntegerField(default=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('we_are_allowed_to_take_pictures_of_you_and_your_guest', models.BooleanField(db_column='picture_consent', default=True)),
                ('we_are_allowed_to_take_pictures_of_your_apartment', models.BooleanField(db_column='apartment_consent', default=True)),
                ('we_are_allowed_to_use_your_event_content_for_our_business_promotions', models.BooleanField(db_column='content_consent', default=True)),
                ('menu_type', models.CharField(choices=[('M1', '3 Course Menu'), ('M2', '4 Course Menu'), ('M3', '5 Course Menu')], default='M1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FineDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('number_of_guest', models.IntegerField(default=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('we_are_allowed_to_take_pictures_of_you_and_your_guest', models.BooleanField(db_column='picture_consent', default=True)),
                ('we_are_allowed_to_take_pictures_of_your_apartment', models.BooleanField(db_column='apartment_consent', default=True)),
                ('we_are_allowed_to_use_your_event_content_for_our_business_promotions', models.BooleanField(db_column='content_consent', default=True)),
                ('menu_type', models.CharField(choices=[('M1', 'Menu 1'), ('M2', 'Menu 2'), ('M3', 'Menu 3'), ('M4', 'Menu 4'), ('M5', 'Menu 5'), ('M6', 'Menu 6'), ('M7', 'Menu 7')], default='M1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('HOME', 'Home'), ('WEDDING', 'Wedding'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('OTHERS', 'Others')], default='HOME', max_length=15)),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
