# Generated by Django 5.0.2 on 2024-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('we_are_allowed_to_take_pictures_of_you_and_your_guest', models.BooleanField(default=True)),
                ('we_are_allowed_to_take_pictures_of_your_apartment', models.BooleanField(default=True)),
                ('we_are_allowed_to_use_your_event_content_for_our_business_promotions', models.BooleanField(default=True)),
                ('number_of_guest', models.CharField(choices=[(10, '10 or less'), (20, '20 or less'), (30, '30 or less'), (40, '40 or less'), (50, '50 or more')], default=10, max_length=2)),
                ('menu_type', models.CharField(choices=[('M1', 'Menu 1'), ('M2', 'Menu 2'), ('M3', 'Menu 3'), ('M4', 'Menu 4'), ('M5', 'Menu 5'), ('M6', 'Menu 6'), ('M7', 'Menu 7')], default='M1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
